### PR TITLE
Added website to about the project

### PR DESCRIPTION
**Pull request by SuperZekes**

### CODE REVIEW

**Comment by DrgnFireYellow** [comment]
These aren't really supposed to have READMEs

**Comment by SuperZekes** [comment]
> These aren't really supposed to have READMEs

I did that so there would be a difference

**Comment by SuperZekes** [comment]
Screenshot 2023-11-27 134027

**Comment by DrgnFireYellow** [comment]
I think pull requests only track files, but I'll link it anyways

**Pull request closed without merging**
